server:
  port: 7799
  servlet:
    context-path: /example

mande:
  url: http://localhost:8080/mande
  appKey: AJ0uiczwGI3Z3KF4/k1cWl4QEXcNWcs4kb1dDaDImVk+7acJ2WVsZSLZCG+SiSJBQLBVAiV2Y6N99YeMlBL6xpRZZPh/dwefdUipm8iuZtm73lKj+oc6C49rrjpdIadS/VHWJXjvECKG8sStP9TnKfJXDbor2ETmMpkMcFKx9jI=

